### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by faassen** [Ff00ff/mammoth-cli#1]
I read with interest about Mammoth and its migration system. The ability to create migrations automatically is appealing - I have used Django's ORM and migration system and it has this capability. But I have a few questions and comments:

How would this deal with migrations that cannot be purely expressed by schema manipulation commands? 

As a schema neutral example consider a migration that turns all field in a column from upper to lower case. 

More complex examples involve both a schema change as well as migration of data. For instance a single varchar column that is split into two columns,the first column getting the first 2 characters and the second the rest.

This migration system has only forward migrations and the suggestion is to add an additional migration to go back again. How does this deal with situations such as switching between git branches where one branch is at an earlier migration than another? This type of situation can also happen with merge conflicts where a migration on one branch could be completely eliminated.

I look forward to reading your thoughts on these matters!

**Comment by martijndeh** [comment]
Great to hear! The cli is in beta still so please take that into account. :)

I think the developer is still responsible to write the migrations. The cli just helps you do the more repetitive tasks such as automatically applying schema changes (alter table statements) for you. I think it's really nice to be able to add some extra column in your application code (your table, repo, etc) and be able to run `mammoth next` to get those changes in a new migration already. To get some form of type-safety I also feel it's a must to have a system look over your migrations as you would never know if your define tables actually match the schema of your database.

The remaining non-schema change queries you still need to write yourself such as add a `using` clause or doing data manipulation queries to update a column's values from upper to lower case. It's perfectly fine for the cli to generate migration 005.sql for you and you go ahead and add some additional statements there. There are more cases where the migration generator doesn't know your intention: consider a simple column rename from `a` to `b`; did you rename the column or did you drop a column and add a new column?

The forward-only migrations may be a bit controversial, but if you have the right processes in place you don't need any rollbacks. Your example specifically I generally do not try to rely on the data in my database too much during development so I can just drop the database and create a new one; apply all migrations and I'm good to go. My tests set up test data and if I really must run a service with specific data I generally have a seeder which fills my database with all types of data I need. Also feel it may be a bit safer to go from 001.sql to 010.sql instead of 005.sql to 004.sql to 010.sql.

I just replied to your questions specifically, and there is so much more to this like your git branching strategy e.g. no git flow, as much trunk-based development, small changes always, etc etc. Let me know what you think or if you have other specific questions.

**Comment by faassen** [comment]
So you propose the data migration is also to be expressed as SQL and not as TS? It's striking to me that mammoth migrations themselves cannot be expressed with mammoth. I was hoping some mechanism could be devised for migrations that are pure TS, and also combined migrations that consist of altering a table as well as some TS code.

**Comment by faassen** [comment]
As to the interaction between migrations and git branches: I agree it depends on your way of working.

**Comment by martijndeh** [comment]
Yes, today, Mammoth migrations are simply written in SQL. In the future Mammoth will also support TypeScript migrations. This totally makes sense, but we have to pick our priorities I'm afraid. There is a lot to do! If you look at the benefits of writing your application code in type-safe queries vs your migrations I think your application code (excluding migrations) benefit the most from the extra type-safety. So all effort now goes into this area, and once this part has matured enough, will start focussing on the migration side of things. :)

**Comment by voxpelli** [comment]
I might have duplicated some of this question as #4, glad that you will support support TypeScript migrations eventually! (And plain JS ones as well I guess)
