### ISSUE TITLE
Enable JS/TS-files for migrations

### ISSUE THREAD

**Issue by voxpelli** [Ff00ff/mammoth-cli#4]
As a follow up to #3:

In knex migrations where plain JS rather than plain SQL as here. I do like the fact that it is plain SQL here and I do would like that to keep being the default, but I would like the opportunity to also add JS-based migrations.

Examples from the project I mentioned in #3:

* A simple table addition would be better of as a plain SQL file as you have done: https://github.com/voxpelli/webpage-webmentions/blob/master/migrations/20150328230212_polite-tables.js
* Though sometimes a migration can be more about normalizing and adapting the data within the tables than its about changing the table itself: https://github.com/voxpelli/webpage-webmentions/blob/master/migrations/20140806201032_never-render-non-http-urls.js That's better of in JS, writing the data adaptions with the core Mammoth library.

What do you think? Does sounds like a decent addition to you?

**Comment by martijndeh** [comment]
I’m not convinced. Personally, I would try to write it out in SQL. If that cannot be done I would probably write a one-off service or script on the application code to perform the changes. Especially if it’s not altering the database schema I feel it’s not really a migration, but just some code you want to run a couple of times. I say a couple of times because, if you have a blue-green or canary deployments, and you can run the migration and still have the “old” part of your system run, it could happen you get some incorrect data after you’ve applied the migrations.

Also, when you say JS I assume you mean TypeScript? If you use JS you can just as well use Knex.js or something because you wouldn’t get the type-safety features of Mammoth anyway.

**Comment by voxpelli** [comment]
> Also, when you say JS I assume you mean TypeScript? If you use JS you can just as well use Knex.js or something because you wouldn’t get the type-safety features of Mammoth anyway.

Not true, you can use TypeScript to ensure type-safety in regular JS: https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html (Which eg. I consider to generally be superior to TypeScript itself as you can get rid of the compilation step)

Anyhow, feel free to close this if it doesn't resonate with you, I'll solve things in another way.

**Comment by martijndeh** [comment]
You are right, JavaScript is also possible. Right now though, this cli will not support anything other than SQL migrations. Perhaps in the future once the Mammoth query builder is more feature-complete with regards to the data definition SQL (create table, alter table, etc) we can consider this again. In any case, right now I feel it's a good thing you can only use SQL, as anything more complex which isn't possible to do in SQL probably does not belong in a migration.
